name: Feature Request
description: Suggest a new feature for WorldSynth
title: "[Feature]: "
labels:
  - "type:feature"
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem would this feature solve? What is your use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, screenshots, audio examples, or links to similar features in other synths.
    validations:
      required: false
