const std = @import("std");
const builtin = @import("builtin");

// ── Wavetable Engine (WP-050) ───────────────────────────────────────
// Mip-mapped wavetable oscillator with Hermite cubic interpolation.
// Max 256 frames x 2048 samples. Mip-maps per octave for band-limited
// playback. Frame position modulatable for wavetable morphing.
// Phase accumulator uses f64 for low-frequency precision.
// No heap allocation — all tables preallocated.

pub const BLOCK_SIZE: usize = 128;
pub const MAX_FRAMES: u32 = 256;
pub const FRAME_SIZE: usize = 2048;
pub const FRAME_MASK: usize = FRAME_SIZE - 1;
pub const MIP_LEVELS: usize = 10;

pub const WavetableEngine = struct {
    const Self = @This();

    /// tables[0] = full harmonics (base frames loaded via load_frame).
    /// tables[1..] = progressively fewer harmonics (generated by generate_mip_maps).
    tables: [MIP_LEVELS][MAX_FRAMES][FRAME_SIZE]f32,
    frame_count: u32,

    /// Initialize by zeroing all tables in-place. Must be called on an
    /// already-allocated instance (heap or static) — the struct is ~20MB
    /// and cannot be returned by value (stack overflow).
    pub fn init(self: *Self) void {
        @memset(std.mem.asBytes(&self.tables), 0);
        self.frame_count = 0;
    }

    /// Load a single frame into level 0 (full harmonics).
    /// Call generate_mip_maps() after loading all frames.
    pub fn load_frame(self: *Self, idx: u32, data: *const [FRAME_SIZE]f32) void {
        @memcpy(&self.tables[0][idx], data);
        if (idx + 1 > self.frame_count) self.frame_count = idx + 1;
    }

    /// Generate mip-mapped versions of all loaded frames via FFT.
    /// For each level, harmonics above the Nyquist limit for that octave
    /// are zeroed. Level n allows max_harmonics = FRAME_SIZE / 2^(n+1).
    pub fn generate_mip_maps(self: *Self) void {
        var re: [FRAME_SIZE]f32 = undefined;
        var im: [FRAME_SIZE]f32 = undefined;
        var mip_re: [FRAME_SIZE]f32 = undefined;
        var mip_im: [FRAME_SIZE]f32 = undefined;

        for (0..self.frame_count) |frame_idx| {
            // FFT the base frame (level 0)
            @memcpy(&re, &self.tables[0][frame_idx]);
            @memset(&im, 0.0);
            fft(&re, &im, false);

            for (1..MIP_LEVELS) |level| {
                @memcpy(&mip_re, &re);
                @memcpy(&mip_im, &im);
                const max_harm = FRAME_SIZE >> @intCast(level + 1);
                // Zero frequency bins above the harmonic limit.
                // Keep bins [0..max_harm] and [N-max_harm..N-1] (mirror).
                if (max_harm > 0 and max_harm < FRAME_SIZE / 2) {
                    for (max_harm + 1..FRAME_SIZE - max_harm) |bin| {
                        mip_re[bin] = 0.0;
                        mip_im[bin] = 0.0;
                    }
                }
                fft(&mip_re, &mip_im, true); // IFFT
                @memcpy(&self.tables[level][frame_idx], &mip_re);
            }
        }
    }

    /// Process one sample with Hermite interpolation and mip-level selection.
    pub inline fn process_sample(
        self: *const Self,
        phase: *f64,
        phase_inc: f64,
        frame_pos: f32,
    ) f32 {
        @setFloatMode(.optimized);
        const level = select_mip_level(@floatCast(phase_inc));
        const fc: f32 = @floatFromInt(self.frame_count -| 1);
        const frac_frame = std.math.clamp(frame_pos, 0.0, 1.0) * fc;
        const frame_idx: u32 = @min(@as(u32, @intFromFloat(frac_frame)), self.frame_count -| 1);
        const frame_frac = frac_frame - @as(f32, @floatFromInt(frame_idx));

        const ph: f32 = @floatCast(phase.*);
        const a = read_hermite(&self.tables[level][frame_idx], ph);
        const next_frame = @min(frame_idx + 1, self.frame_count -| 1);
        const b = read_hermite(&self.tables[level][next_frame], ph);
        const result = @mulAdd(f32, b - a, frame_frac, a);

        phase.* += phase_inc;
        if (phase.* >= 1.0) phase.* -= 1.0;
        return result;
    }

    /// Process a block of 128 samples.
    pub fn process_block(
        self: *const Self,
        out: *[BLOCK_SIZE]f32,
        phase: *f64,
        phase_inc: f64,
        frame_pos: f32,
    ) void {
        for (out) |*s| {
            s.* = self.process_sample(phase, phase_inc, frame_pos);
        }
    }

    /// Process a block with linear interpolation (for benchmark comparison).
    pub fn process_block_linear(
        self: *const Self,
        out: *[BLOCK_SIZE]f32,
        phase: *f64,
        phase_inc: f64,
        frame_pos: f32,
    ) void {
        const level = select_mip_level(@floatCast(phase_inc));
        const fc: f32 = @floatFromInt(self.frame_count -| 1);
        const frac_frame = std.math.clamp(frame_pos, 0.0, 1.0) * fc;
        const frame_idx: u32 = @min(@as(u32, @intFromFloat(frac_frame)), self.frame_count -| 1);
        const frame_frac = frac_frame - @as(f32, @floatFromInt(frame_idx));
        const next_frame = @min(frame_idx + 1, self.frame_count -| 1);

        for (out) |*s| {
            const ph: f32 = @floatCast(phase.*);
            const a = read_linear(&self.tables[level][frame_idx], ph);
            const b = read_linear(&self.tables[level][next_frame], ph);
            s.* = @mulAdd(f32, b - a, frame_frac, a);
            phase.* += phase_inc;
            if (phase.* >= 1.0) phase.* -= 1.0;
        }
    }
};

// ── Interpolation & Mip-Level Selection ──────────────────────────────

/// Hermite cubic interpolation (4-point, 3rd-order polynomial).
/// Reduces interpolation noise by ~40dB vs linear.
inline fn hermite(y0: f32, y1: f32, y2: f32, y3: f32, frac: f32) f32 {
    const c1 = 0.5 * (y2 - y0);
    const c2 = y0 - 2.5 * y1 + 2.0 * y2 - 0.5 * y3;
    const c3 = 0.5 * (y3 - y0) + 1.5 * (y1 - y2);
    return @mulAdd(f32, @mulAdd(f32, @mulAdd(f32, c3, frac, c2), frac, c1), frac, y1);
}

/// Read one sample from a frame with Hermite interpolation.
inline fn read_hermite(table: *const [FRAME_SIZE]f32, phase: f32) f32 {
    const idx_f = phase * @as(f32, @floatFromInt(FRAME_SIZE));
    const idx: usize = @min(@as(usize, @intFromFloat(idx_f)), FRAME_SIZE - 1);
    const frac = idx_f - @as(f32, @floatFromInt(idx));
    return hermite(
        table[(idx -% 1) & FRAME_MASK],
        table[idx & FRAME_MASK],
        table[(idx + 1) & FRAME_MASK],
        table[(idx + 2) & FRAME_MASK],
        frac,
    );
}

/// Read one sample from a frame with linear interpolation (benchmark comparison).
inline fn read_linear(table: *const [FRAME_SIZE]f32, phase: f32) f32 {
    const idx_f = phase * @as(f32, @floatFromInt(FRAME_SIZE));
    const idx: usize = @min(@as(usize, @intFromFloat(idx_f)), FRAME_SIZE - 1);
    const frac = idx_f - @as(f32, @floatFromInt(idx));
    const a = table[idx & FRAME_MASK];
    return @mulAdd(f32, table[(idx + 1) & FRAME_MASK] - a, frac, a);
}

/// Select mip level based on phase increment.
/// Higher phase_inc → higher level → fewer harmonics.
inline fn select_mip_level(phase_inc: f32) usize {
    if (phase_inc <= 0.0) return 0;
    const product = @as(f32, @floatFromInt(FRAME_SIZE)) * phase_inc;
    if (product <= 1.0) return 0;
    const log_val = @log2(product);
    const level: usize = @intFromFloat(@ceil(log_val));
    return @min(level, MIP_LEVELS - 1);
}

// ── Radix-2 FFT/IFFT ────────────────────────────────────────────────

/// In-place radix-2 decimation-in-time FFT (inverse=false) or IFFT (inverse=true).
fn fft(re: *[FRAME_SIZE]f32, im: *[FRAME_SIZE]f32, inverse: bool) void {
    const n = FRAME_SIZE;
    // Bit-reversal permutation
    var j: usize = 0;
    for (1..n) |i| {
        var bit: usize = n >> 1;
        while (j & bit != 0) {
            j ^= bit;
            bit >>= 1;
        }
        j ^= bit;
        if (i < j) {
            std.mem.swap(f32, &re[i], &re[j]);
            std.mem.swap(f32, &im[i], &im[j]);
        }
    }
    // Butterfly stages
    var len: usize = 2;
    while (len <= n) : (len <<= 1) {
        const sign: f64 = if (inverse) -1.0 else 1.0;
        const angle: f64 = 2.0 * std.math.pi / @as(f64, @floatFromInt(len)) * sign;
        const wlen_re: f32 = @floatCast(@cos(angle));
        const wlen_im: f32 = @floatCast(@sin(angle));
        var i: usize = 0;
        while (i < n) : (i += len) {
            var w_re: f32 = 1.0;
            var w_im: f32 = 0.0;
            for (0..len / 2) |k| {
                const u_re = re[i + k];
                const u_im = im[i + k];
                const v_re = re[i + k + len / 2] * w_re - im[i + k + len / 2] * w_im;
                const v_im = re[i + k + len / 2] * w_im + im[i + k + len / 2] * w_re;
                re[i + k] = u_re + v_re;
                im[i + k] = u_im + v_im;
                re[i + k + len / 2] = u_re - v_re;
                im[i + k + len / 2] = u_im - v_im;
                const new_w_re = w_re * wlen_re - w_im * wlen_im;
                w_im = w_re * wlen_im + w_im * wlen_re;
                w_re = new_w_re;
            }
        }
    }
    // Scale IFFT output
    if (inverse) {
        const scale: f32 = 1.0 / @as(f32, @floatFromInt(n));
        for (re, im) |*r, *m| {
            r.* *= scale;
            m.* *= scale;
        }
    }
}

// ── Test Helpers ─────────────────────────────────────────────────────

/// Generate a single-cycle sine wave into a frame buffer.
fn generate_sine_frame(buf: *[FRAME_SIZE]f32) void {
    for (buf, 0..) |*s, i| {
        s.* = @sin(2.0 * std.math.pi * @as(f32, @floatFromInt(i)) / @as(f32, @floatFromInt(FRAME_SIZE)));
    }
}

/// Generate a single-cycle saw wave into a frame buffer (naive, full harmonics).
fn generate_saw_frame(buf: *[FRAME_SIZE]f32) void {
    for (buf, 0..) |*s, i| {
        const t: f32 = @as(f32, @floatFromInt(i)) / @as(f32, @floatFromInt(FRAME_SIZE));
        s.* = 2.0 * t - 1.0;
    }
}

// ── Tests ────────────────────────────────────────────────────────────

test "AC-1: Sine wavetable at 440Hz — error < 1e-3 vs sin()" {
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    wt.load_frame(0, &sine_frame);
    wt.generate_mip_maps();

    const sample_rate: f64 = 44100.0;
    const freq: f64 = 440.0;
    const phase_inc: f64 = freq / sample_rate;
    var phase: f64 = 0.0;

    var out: [BLOCK_SIZE]f32 = undefined;
    wt.process_block(&out, &phase, phase_inc, 0.0);

    // Compare against reference sin()
    var ref_phase: f64 = 0.0;
    var max_err: f32 = 0.0;
    for (out) |s| {
        const ref: f32 = @floatCast(@sin(2.0 * std.math.pi * ref_phase));
        const err = @abs(s - ref);
        max_err = @max(max_err, err);
        ref_phase += phase_inc;
    }
    std.debug.print("\n[WP-050] Sine 440Hz max error: {d:.6}\n", .{max_err});
    try std.testing.expect(max_err < 1e-3);
}

test "AC-2: Frame position 0.5 interpolates between frames" {
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    var saw_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    generate_saw_frame(&saw_frame);
    wt.load_frame(0, &sine_frame);
    wt.load_frame(1, &saw_frame);
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;

    // Process at frame_pos = 0.0 (pure sine)
    var phase0: f64 = 0.0;
    var out0: [BLOCK_SIZE]f32 = undefined;
    wt.process_block(&out0, &phase0, phase_inc, 0.0);

    // Process at frame_pos = 1.0 (pure saw)
    var phase1: f64 = 0.0;
    var out1: [BLOCK_SIZE]f32 = undefined;
    wt.process_block(&out1, &phase1, phase_inc, 1.0);

    // Process at frame_pos = 0.5 (blend)
    var phase_mid: f64 = 0.0;
    var out_mid: [BLOCK_SIZE]f32 = undefined;
    wt.process_block(&out_mid, &phase_mid, phase_inc, 0.5);

    // The blend output must differ from both pure sine and pure saw
    var diff_sine: f32 = 0.0;
    var diff_saw: f32 = 0.0;
    for (out_mid, out0, out1) |mid, s, w| {
        diff_sine += @abs(mid - s);
        diff_saw += @abs(mid - w);
    }
    std.debug.print("\n[WP-050] Frame blend diff vs sine: {d:.4}, vs saw: {d:.4}\n", .{ diff_sine, diff_saw });
    try std.testing.expect(diff_sine > 0.01);
    try std.testing.expect(diff_saw > 0.01);
}

test "AC-N1: no NaN/Inf after 44100 samples" {
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var saw_frame: [FRAME_SIZE]f32 = undefined;
    generate_saw_frame(&saw_frame);
    wt.load_frame(0, &saw_frame);
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;
    var phase: f64 = 0.0;
    var out: [BLOCK_SIZE]f32 = undefined;

    // Process 44100 samples (345 blocks)
    for (0..345) |_| {
        wt.process_block(&out, &phase, phase_inc, 0.0);
        for (out) |s| {
            try std.testing.expect(!std.math.isNan(s));
            try std.testing.expect(!std.math.isInf(s));
        }
    }
}

test "mip-level selection correctness" {
    // Very low frequency → level 0 (product = 2048 * 20/44100 ≈ 0.93 < 1)
    try std.testing.expectEqual(@as(usize, 0), select_mip_level(20.0 / 44100.0));
    // 440Hz → level 5 (product = 2048 * 440/44100 ≈ 20.4, ceil(log2(20.4)) = 5)
    try std.testing.expectEqual(@as(usize, 5), select_mip_level(440.0 / 44100.0));
    // Very high frequency → high mip level
    const high_level = select_mip_level(10000.0 / 44100.0);
    try std.testing.expect(high_level > 5);
    // Negative/zero → level 0
    try std.testing.expectEqual(@as(usize, 0), select_mip_level(0.0));
    try std.testing.expectEqual(@as(usize, 0), select_mip_level(-1.0));
}

test "phase wrapping stays in [0, 1)" {
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    wt.load_frame(0, &sine_frame);
    wt.frame_count = 1;

    var phase: f64 = 0.99;
    const phase_inc: f64 = 440.0 / 44100.0;
    var out: [BLOCK_SIZE]f32 = undefined;
    wt.process_block(&out, &phase, phase_inc, 0.0);
    try std.testing.expect(phase >= 0.0);
    try std.testing.expect(phase < 1.0);
}

test "FFT/IFFT roundtrip preserves signal" {
    var re: [FRAME_SIZE]f32 = undefined;
    var im = [_]f32{0.0} ** FRAME_SIZE;
    // Fill with a known signal (sine at bin 10)
    for (&re, 0..) |*s, i| {
        s.* = @sin(2.0 * std.math.pi * 10.0 * @as(f32, @floatFromInt(i)) / @as(f32, @floatFromInt(FRAME_SIZE)));
    }
    var original: [FRAME_SIZE]f32 = undefined;
    @memcpy(&original, &re);

    fft(&re, &im, false); // Forward FFT
    fft(&re, &im, true); // Inverse FFT

    var max_err: f32 = 0.0;
    for (re, original) |r, o| {
        max_err = @max(max_err, @abs(r - o));
    }
    std.debug.print("\n[WP-050] FFT roundtrip max error: {d:.8}\n", .{max_err});
    try std.testing.expect(max_err < 1e-4);
}

test "frame_pos endpoints select correct frames" {
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    var saw_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    generate_saw_frame(&saw_frame);
    wt.load_frame(0, &sine_frame);
    wt.load_frame(1, &saw_frame);
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;

    // frame_pos=0 should match sine
    var p0: f64 = 0.25; // quarter phase
    const s0 = wt.process_sample(&p0, phase_inc, 0.0);
    var p1: f64 = 0.25;
    const s1 = wt.process_sample(&p1, phase_inc, 1.0);

    // They should be different (sine vs saw at same phase)
    try std.testing.expect(@abs(s0 - s1) > 0.01);
}

test "process_block matches sequential process_sample" {
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    wt.load_frame(0, &sine_frame);
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;

    var phase_block: f64 = 0.0;
    var block_out: [BLOCK_SIZE]f32 = undefined;
    wt.process_block(&block_out, &phase_block, phase_inc, 0.0);

    var phase_seq: f64 = 0.0;
    for (block_out) |b| {
        const s = wt.process_sample(&phase_seq, phase_inc, 0.0);
        try std.testing.expectApproxEqAbs(b, s, 1e-6);
    }
}

// ── Benchmarks ──────────────────────────────────────────────────────

test "benchmark: Wavetable process_block (Hermite)" {
    const strict = builtin.mode == .ReleaseFast or builtin.mode == .ReleaseSmall;
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    wt.load_frame(0, &sine_frame);
    wt.load_frame(1, &sine_frame); // 2 frames for morphing
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;
    var out: [BLOCK_SIZE]f32 = undefined;

    // Warmup
    var phase: f64 = 0.0;
    for (0..1000) |_| wt.process_block(&out, &phase, phase_inc, 0.0);

    const iterations: u64 = if (strict) 1_000_000 else 50_000;
    phase = 0.0;
    var timer = std.time.Timer.start() catch unreachable;
    for (0..iterations) |_| {
        wt.process_block(&out, &phase, phase_inc, 0.0);
        std.mem.doNotOptimizeAway(&out);
    }
    const ns = timer.read() / iterations;

    const budget: u64 = if (strict) 2000 else 100_000;
    const pass = ns < budget;
    std.debug.print("\n[WP-050] Hermite process_block: {}ns/block (budget: {}ns) {s}\n", .{ ns, budget, if (pass) "PASS" else "<<< FAIL >>>" });
    try std.testing.expect(pass);
}

test "benchmark: Mip-Map Lookup (no morphing)" {
    const strict = builtin.mode == .ReleaseFast or builtin.mode == .ReleaseSmall;
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    wt.load_frame(0, &sine_frame);
    wt.generate_mip_maps();

    // High frequency to exercise mip-level selection
    const phase_inc: f64 = 4000.0 / 44100.0;
    var out: [BLOCK_SIZE]f32 = undefined;
    var phase: f64 = 0.0;

    for (0..1000) |_| wt.process_block(&out, &phase, phase_inc, 0.0);

    const iterations: u64 = if (strict) 1_000_000 else 50_000;
    phase = 0.0;
    var timer = std.time.Timer.start() catch unreachable;
    for (0..iterations) |_| {
        wt.process_block(&out, &phase, phase_inc, 0.0);
        std.mem.doNotOptimizeAway(&out);
    }
    const ns = timer.read() / iterations;

    const budget: u64 = if (strict) 1500 else 80_000;
    const pass = ns < budget;
    std.debug.print("\n[WP-050] Mip-Map Lookup: {}ns/block (budget: {}ns) {s}\n", .{ ns, budget, if (pass) "PASS" else "<<< FAIL >>>" });
    try std.testing.expect(pass);
}

test "benchmark: Frame Morphing" {
    const strict = builtin.mode == .ReleaseFast or builtin.mode == .ReleaseSmall;
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    var saw_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    generate_saw_frame(&saw_frame);
    wt.load_frame(0, &sine_frame);
    wt.load_frame(1, &saw_frame);
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;
    var out: [BLOCK_SIZE]f32 = undefined;
    var phase: f64 = 0.0;

    for (0..1000) |_| wt.process_block(&out, &phase, phase_inc, 0.5);

    const iterations: u64 = if (strict) 1_000_000 else 50_000;
    phase = 0.0;
    var timer = std.time.Timer.start() catch unreachable;
    for (0..iterations) |_| {
        wt.process_block(&out, &phase, phase_inc, 0.5);
        std.mem.doNotOptimizeAway(&out);
    }
    const ns = timer.read() / iterations;

    const budget: u64 = if (strict) 2500 else 120_000;
    const pass = ns < budget;
    std.debug.print("\n[WP-050] Frame Morphing: {}ns/block (budget: {}ns) {s}\n", .{ ns, budget, if (pass) "PASS" else "<<< FAIL >>>" });
    try std.testing.expect(pass);
}

test "benchmark: Hermite vs Linear overhead" {
    const strict = builtin.mode == .ReleaseFast or builtin.mode == .ReleaseSmall;
    const wt = try std.testing.allocator.create(WavetableEngine);
    defer std.testing.allocator.destroy(wt);
    wt.init();

    var sine_frame: [FRAME_SIZE]f32 = undefined;
    generate_sine_frame(&sine_frame);
    wt.load_frame(0, &sine_frame);
    wt.generate_mip_maps();

    const phase_inc: f64 = 440.0 / 44100.0;
    var out: [BLOCK_SIZE]f32 = undefined;

    // Warmup both
    var phase: f64 = 0.0;
    for (0..1000) |_| wt.process_block(&out, &phase, phase_inc, 0.0);
    phase = 0.0;
    for (0..1000) |_| wt.process_block_linear(&out, &phase, phase_inc, 0.0);

    const iterations: u64 = if (strict) 1_000_000 else 50_000;

    // Measure Hermite
    phase = 0.0;
    var timer_h = std.time.Timer.start() catch unreachable;
    for (0..iterations) |_| {
        wt.process_block(&out, &phase, phase_inc, 0.0);
        std.mem.doNotOptimizeAway(&out);
    }
    const ns_hermite = timer_h.read() / iterations;

    // Measure Linear
    phase = 0.0;
    var timer_l = std.time.Timer.start() catch unreachable;
    for (0..iterations) |_| {
        wt.process_block_linear(&out, &phase, phase_inc, 0.0);
        std.mem.doNotOptimizeAway(&out);
    }
    const ns_linear = timer_l.read() / iterations;

    const ratio: f64 = if (ns_linear > 0) @as(f64, @floatFromInt(ns_hermite)) / @as(f64, @floatFromInt(ns_linear)) else 0.0;
    // In debug mode, inline hints are ignored, so Hermite overhead is much higher.
    // Only enforce the ratio in ReleaseFast.
    // Hermite: 4 table reads + cubic polynomial (~10 FMA ops)
    // Linear: 2 table reads + 1 lerp — ratio ~2-3x is expected.
    const max_ratio: f64 = if (strict) 2.5 else 10.0;
    const pass = ratio < max_ratio;
    std.debug.print("\n[WP-050] Hermite: {}ns, Linear: {}ns, ratio: {d:.2}x (max: {d:.1}x) {s}\n", .{ ns_hermite, ns_linear, ratio, max_ratio, if (pass) "PASS" else "<<< FAIL >>>" });
    try std.testing.expect(pass);
}
